3rdSemesterProject/WebMVC/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace WebMVC.Controllers
{
    /*
     This controller's only purpose is the MVC being able to display the Contact page by calling the Index method
     */
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

3rdSemesterProject/WebMVC/Controllers/DeveloperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebMVC.RestClientLayer;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class DeveloperController : Controller
    {
        ApiDeveloperDataAccess _dataAccess = new("https://localhost:7023/api/v1/developer");
        
        // GET: Developer
        // Returns a list view after taking an IEnumerable<Developer> as a parameter
        public ActionResult Index()
        {
            return View(_dataAccess.GetAllDevelopers());
        }
    }
}

3rdSemesterProject/WebMVC/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebMVC.RestClientLayer;
using WebMVC.Models;

namespace WebMVC.Controllers
{
    public class EventController : Controller
    {
        // Uses 3 data access obejcts, the Event and Member are needed for functionality, whereas the EventMember accesses the connection table
        ApiEventDataAccess _dataAccessEvent = new("https://localhost:7023/api/v1/Event");
		ApiMemberDataAccess _dataAccessMember = new("https://localhost:7023/api/v1/Member");
		ApiEventMemberDataAccess _dataAccessEventMember = new("https://localhost:7023/api/v1/EventMember");

		// GET: Event
        // Returns a detail view of a single event after taking an Event object as parameter
		[HttpGet]
        public ActionResult Index()
        {
            return View(_dataAccessEvent.GetUpcomingEvent());
        }

		[HttpGet]
        public string GetMemberAmount(int eventId)
		{
            return _dataAccessEventMember.GetMemberAmount(eventId);
		}

        [HttpPost]
        public bool JoinEvent([FromBody] EventJoinData data)
		{
            Member member;
            try
            {
                member = _dataAccessMember.GetAllMembers().First(m => m.Email == data.MemberEmail); //tries to find a member with matching email
            }
            catch(Exception ex) //we don't have a member with the given email address
			{
                _dataAccessMember.CreateMember(data.MemberEmail); //create Member
				member = _dataAccessMember.GetAllMembers().First(m => m.Email == data.MemberEmail); //get Member again, now that it exists
			}
            EventMember eventMember = new(data.EventId, member.MemberId);
            return _dataAccessEventMember.JoinEvent(eventMember);
		}

        // Class for creating objects from fetched data
        public class EventJoinData
		{
			public int EventId { get; private set; }
			public string MemberEmail { get; private set; }
            public EventJoinData(int eventId, string memberEmail)
			{
                EventId = eventId;
                MemberEmail = memberEmail;
			}
		}
    }
}

3rdSemesterProject/WebMVC/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebMVC.RestClientLayer;
using WebMVC.Models;

namespace WebMVC.Controllers
{

	public class GameController : Controller
    {

        ApiGameDataAccess _dataAccess = new("https://localhost:7023/api/v1/game");

        // GET: Game
        // Returns a lsit view of games after taking an IEnmureable<Game> as parameter
        public ActionResult Index()
        {
            return View(_dataAccess.GetAllGames());
        }

        // GET: Game/Details/5
        // Returns a detail view of a game after taking a Game object as parameter
        public ActionResult Details(int id)
        {
            return View(_dataAccess.GetGameUsingId(id));
        }

        // Called when a game is bought or download link is clicked on the website
        [HttpGet]
        public FileResult DownloadGame(int gameId)
		{
            Game gameToDownload = _dataAccess.GetGameFileById(gameId);
            return File(gameToDownload.FileContent, System.Net.Mime.MediaTypeNames.Application.Octet, gameToDownload.FileName);
		}
    }
}

3rdSemesterProject/WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/WebMVC.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="/css/site.css" />
</head>
<body style="background-image:url(/images/background.jpeg)">
    <header>

        <ul class="navbar">
            <a asp-area="" asp-controller="Home" asp-action="Index">
            <li class="nav-item">Home</li></a>
            <a asp-area="" asp-controller="Game" asp-action="Index">
            <li class="nav-item">Games</li></a>
            <a asp-area="" asp-controller="Developer" asp-action="Index">
            <li class="nav-item">Developers</li></a>
            <a asp-area="" asp-controller="Event" asp-action="Index">
            <li class="nav-item">Event</li></a>
            <a asp-area="" asp-controller="Contact" asp-action="Index">
            <li class="nav-item" style="float:right">Contact</li></a>
        </ul>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("script", false/*required*/)
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>